(set-option :produce-unsat-cores true) ; enable generation of unsat cores
(set-option :produce-models true) ; enable model generation
(set-logic ALL)
(declare-sort var2925 0)
(declare-sort var1042 0)
(declare-sort var3512 0)
(declare-sort var3324 0)
(declare-sort void 0)
(declare-sort Iterator 0)
(declare-sort ClassObject 0)
(declare-fun var2925_size/-959786421 (var2925) Int)
(declare-fun String-init () String)
(define-fun <init>/1968657023 () String "")
(define-fun append/672562846 ((s String) (tail String)) String (str.++ s tail))
(declare-fun var2925_get/-1216255739 (var2925 Int) var3512)
(declare-fun cast-from-var3512-to-String (var3512) String)
(define-fun toString/-2075883882 ((s String)) String s)
(define-fun length/-134980193 ((s String)) Int (str.len s))
(declare-fun var3324_addUnicodeEscapes/1686793564 (String) String)
(declare-const null-var2925 var2925)
(declare-const null-String String)
(declare-const var729 var2925) ; Statement: r0 := @parameter0: java.util.List 
(assert (not (= var729 null-var2925)))
(declare-const var171 String) ; Statement: r9 := @parameter1: java.lang.String 
(assert (not (= var171 null-String)))
(define-const var1393 String "Generated By:") ; Statement: r22 = "Generated By:" 
(define-const var1720 Int 0) ; Statement: i3 = 0 
(assert true) ; Non Conditional
(define-const var2196 Int (var2925_size/-959786421 var729)) ; Statement: $i0 = interfaceinvoke r0.<java.util.List: int size()>() 
(define-const var2777 Int (- var2196 1)) ; Statement: $i1 = $i0 - 1 
 ; Statement: if i3 >= $i1 goto $r1 = new java.lang.StringBuilder 
(assert (>= var1720 var2777)) ; Cond: i3 >= $i1 
(define-const var1477 String String-init) ; Statement: $r1 = new java.lang.StringBuilder 
(assert true)
;(assert (<init>/1968657023 var1477)) ; Statement: specialinvoke $r1.<java.lang.StringBuilder: void <init>()>() 
(declare-const var1477!1 String)
(assert (= var1477!1 ""))
(assert true)
(define-const var2517 String (append/672562846 var1477!1 var1393)) ; Statement: $r4 = virtualinvoke $r1.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r22) 
(declare-const var1477!2 String)
(assert (= var1477!2 (str.++ var1477!1 var1393)))
(define-const var2077 var3512 (var2925_get/-1216255739 var729 var1720)) ; Statement: $r2 = interfaceinvoke r0.<java.util.List: java.lang.Object get(int)>(i3) 
(define-const var3104 String (cast-from-var3512-to-String var2077)) ; Statement: $r3 = (java.lang.String) $r2 
(assert true)
(define-const var577 String (append/672562846 var2517 var3104)) ; Statement: $r5 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r3) 
(declare-const var2517!1 String)
(assert (= var2517!1 (str.++ var2517 var3104)))
(assert true)
(define-const var405 String (append/672562846 var577 ":")) ; Statement: $r6 = virtualinvoke $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(":") 
(declare-const var577!1 String)
(assert (= var577!1 (str.++ var577 ":")))
(assert true)
(define-const var1549 String (toString/-2075883882 var405)) ; Statement: r23 = virtualinvoke $r6.<java.lang.StringBuilder: java.lang.String toString()>() 
(assert true)
(define-const var2904 Int (length/-134980193 var1549)) ; Statement: $i2 = virtualinvoke r23.<java.lang.String: int length()>() 
 ; Statement: if $i2 <= 200 goto $r7 = new java.lang.StringBuilder 
(assert (<= var2904 200)) ; Cond: $i2 <= 200 
(define-const var3055 String String-init) ; Statement: $r7 = new java.lang.StringBuilder 
(assert true)
;(assert (<init>/1968657023 var3055)) ; Statement: specialinvoke $r7.<java.lang.StringBuilder: void <init>()>() 
(declare-const var3055!1 String)
(assert (= var3055!1 ""))
(assert true)
(define-const var2253 String (append/672562846 var3055!1 var1549)) ; Statement: $r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r23) 
(declare-const var3055!2 String)
(assert (= var3055!2 (str.++ var3055!1 var1549)))
(assert true)
(define-const var342 String (append/672562846 var2253 " Do not edit this line. ")) ; Statement: $r11 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" Do not edit this line. ") 
(declare-const var2253!1 String)
(assert (= var2253!1 (str.++ var2253 " Do not edit this line. ")))
(define-const var3567 String (var3324_addUnicodeEscapes/1686793564 var171)) ; Statement: $r10 = staticinvoke <org.javacc.parser.JavaCCGlobals: java.lang.String addUnicodeEscapes(java.lang.String)>(r9) 
(assert true)
(define-const var283 String (append/672562846 var342 var3567)) ; Statement: $r12 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r10) 
(declare-const var342!1 String)
(assert (= var342!1 (str.++ var342 var3567)))
(assert true)
(define-const var3580 String (toString/-2075883882 var283)) ; Statement: $r13 = virtualinvoke $r12.<java.lang.StringBuilder: java.lang.String toString()>() 
 ; Statement: return $r13 
(check-sat)
(get-model)
(get-unsat-core)
; {var2925_size/-959786421=([java.util.List], int), String-init=([], java.lang.StringBuilder), <init>/1968657023=([java.lang.StringBuilder], void), append/672562846=([java.lang.StringBuilder, java.lang.String], java.lang.StringBuilder), var2925_get/-1216255739=([java.util.List, int], java.lang.Object), cast-from-var3512-to-String=([java.lang.Object], java.lang.String), toString/-2075883882=([java.lang.StringBuilder], java.lang.String), length/-134980193=([java.lang.String], int), var3324_addUnicodeEscapes/1686793564=([java.lang.String], java.lang.String)}
; {var2925=java.util.List, var729=r0, var171=r9, var1042=null_type, var1393=r22, var1720=i3, var2196=$i0, var2777=$i1, var1477=$r1, var2517=$r4, var3512=java.lang.Object, var2077=$r2, var3104=$r3, var577=$r5, var405=$r6, var1549=r23, var2904=$i2, var3055=$r7, var2253=$r8, var342=$r11, var3324=org.javacc.parser.JavaCCGlobals, var3567=$r10, var283=$r12, var3580=$r13}
; {java.util.List=var2925, r0=var729, r9=var171, null_type=var1042, r22=var1393, i3=var1720, $i0=var2196, $i1=var2777, $r1=var1477, $r4=var2517, java.lang.Object=var3512, $r2=var2077, $r3=var3104, $r5=var577, $r6=var405, r23=var1549, $i2=var2904, $r7=var3055, $r8=var2253, $r11=var342, org.javacc.parser.JavaCCGlobals=var3324, $r10=var3567, $r12=var283, $r13=var3580}
;seq <java.lang.StringBuilder: void <init>()>;	<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>;	<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>;	<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>;	<java.lang.StringBuilder: java.lang.String toString()>;	<java.lang.String: int length()>;	<java.lang.StringBuilder: void <init>()>;	<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>;	<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>;	<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>;	<java.lang.StringBuilder: java.lang.String toString()>
;cnt {"<java.lang.StringBuilder: void <init>()>": 2,"<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>": 6,"<java.lang.StringBuilder: java.lang.String toString()>": 2,"<java.lang.String: int length()>": 1}
;stmts r0 := @parameter0: java.util.List;	r9 := @parameter1: java.lang.String;	r22 = "Generated By:";	i3 = 0;	$i0 = interfaceinvoke r0.<java.util.List: int size()>();	$i1 = $i0 - 1;	if i3 >= $i1 goto $r1 = new java.lang.StringBuilder;	$r1 = new java.lang.StringBuilder;	specialinvoke $r1.<java.lang.StringBuilder: void <init>()>();	$r4 = virtualinvoke $r1.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r22);	$r2 = interfaceinvoke r0.<java.util.List: java.lang.Object get(int)>(i3);	$r3 = (java.lang.String) $r2;	$r5 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r3);	$r6 = virtualinvoke $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(":");	r23 = virtualinvoke $r6.<java.lang.StringBuilder: java.lang.String toString()>();	$i2 = virtualinvoke r23.<java.lang.String: int length()>();	if $i2 <= 200 goto $r7 = new java.lang.StringBuilder;	$r7 = new java.lang.StringBuilder;	specialinvoke $r7.<java.lang.StringBuilder: void <init>()>();	$r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r23);	$r11 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" Do not edit this line. ");	$r10 = staticinvoke <org.javacc.parser.JavaCCGlobals: java.lang.String addUnicodeEscapes(java.lang.String)>(r9);	$r12 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r10);	$r13 = virtualinvoke $r12.<java.lang.StringBuilder: java.lang.String toString()>();	return $r13
;block_num 4